### ISSUE TITLE
FIx for weird code block font sizing on IOS

### ISSUE THREAD

**Issue by nathan-barry** [git-bruh/git-bruh.github.io#1]
I was reading your site while on the toilet and saw that the font sizing for code blocks was out of whack, with random lines being double the font size (see image below)

![IMG_9051](https://github.com/git-bruh/site/assets/38043930/e8004525-b329-46e0-90a6-cd21d84c3926)

I once had this problem on my own site. I believe adding this CSS fixed it for me.

```css
/* Fixes iOS font sizing anomaly */
code {
    text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -moz-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
```
